skip_tags: true
clone_depth: 50

os: Visual Studio 2015

environment:
  matrix:
    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86_64"
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86"
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"

platform:
    - x64

build_script:
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda$env:PY_MAJOR_VER-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - cmd: SET PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
  - cmd: conda config --set always_yes yes
  - cmd: conda update conda --quiet
  - cmd: conda install numpy cython pytest pandas scipy patsy statsmodels matplotlib numba nbconvert nbformat pip pyyaml setuptools pyqt pyparsing --quiet
  # Temporary workaround for conda packing issues
  - cmd: conda install "testpath<0.4"
  - cmd: python -m pip install --upgrade pip
  - cmd: pip install pytest-xdist cached_property
  - cmd: python setup.py develop

test_script:
  - cmd: py.test -n 2 arch
