[build-system]
requires = [
  "setuptools",
  "wheel",
  "oldest-supported-numpy",
  "numpy; python_version>='3.11'",
  "Cython>=0.29.24"
]

[tool.black]
target-version = ['py38', 'py39', 'py310']
exclude = '''
(
    \.egg
  | \.git
  | \.mypy_cache
  | \.oytest_cache
  | _build
  | buck-out
  | build
  | dist
)
'''
