package:
  name: arch
  version: "3.2"

source:
  git_url: https://github.com/bashtage/arch.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - scipy
    - pandas
    - patsy
    - statsmodels
    - matplotlib
    - nbconvert
    - pywin32 # [win]

  run:
    - python
    - setuptools
    - cython
    - numpy
    - scipy
    - pandas
    - patsy
    - statsmodels
    - matplotlib
    - pywin32 # [win]

test:
  imports:
    - arch
  requires:
    - pytest

about:
  home: https://github.com/bashtage/arch
  license : NSCA