package:
  name: arch
  version: "4.1"

source:
  git_url: https://github.com/bashtage/arch.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
    - scipy
    - pandas
    - patsy
    - statsmodels
    - matplotlib
    - nbconvert
    - nbformat
    - numba
    - pywin32 # [win]

  run:
    - python
    - setuptools
    - cython
    - numpy x.x
    - scipy
    - pandas
    - patsy
    - statsmodels
    - matplotlib
    - numba
    - pywin32 # [win]


test:
  requires:
    - pytest
  test:
    run_test.sh # [unix]
    run_test.bat # [win]

about:
  home: https://github.com/bashtage/arch
  license : NSCA